Lab 1
aakogtenkov/Ask-me-if-you-can pull request #1
Opened 2016-11-20 16:37 UTC by aakogtenkov

2016-11-20 18:59 UTC, PavelOstyakov requested changes

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +X_t = X.transpose()
Можно вмето X.transpose() писать просто X.T

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +w_r = w[:2]
А зачем это?

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +w = numpy.dot(numpy.dot(numpy.linalg.inv(numpy.dot(X_t, X)), X_t), Y)
Стоит разбить на несколько частей, тяжёло для восприятия, когда много функций сразу

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +sigma = 5
Константы большими буквами

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +p1 = pyplot.scatter(first_cloud[0], first_cloud[1], 28, "red")
Ты ведь нигде не используешь p1, зачем сохранять это?

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +p2 = pyplot.scatter(second_cloud[0], second_cloud[1], 28, "blue")
Аналогично комментарию про p1

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +Point1 = [-MAX_X, (-w[2] + w[0] * MAX_X) / w[1]]
Раз так, то стоит ввести MIN_X. Ну или назвать константу как-нибудь X_LIM, к примеру

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +Mx_min = -1 #M=y(x)*(wx+b)
Плохое название констант. Всё нужно писать заглавными

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +Q1_list = [max(0, 1 - M) for M in Mx_list]
Плохое название. По слову "list" я не смогу догадаться, что у тебя тут лежит список со значением функции в каких-то точках.

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +import random
А зачем ты в каждой ячейке делаешь повторяющиеся импорты?

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    return 2 * (x**2) + y**2 + 2
Странно очень. Выше в комментарии написана другая функция

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +eps = 0.01
Тут стоит сделать функцию def gradient_descent, которая на вход принимает параметры вроде learning_rate, eps и так далее, а отдаёт готовое решение

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +while (learning_rate > eps):
А если у нас так вышло, что это условие никогда не выполняется? Стоит сделать критерий останова по числу итераций

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +list_y = [y]
Плохое название

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    (x, y) = (x_new, y_new)
А зачем тут скобки вообще?

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    level_points_x = mlab.frange(-math.sqrt((level-2) / 2) + 0.01, math.sqrt((level-2) / 2) - 0.01, 0.02)
Слишком длинная и непонятная строка

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +        learning_rate *= 0.5
Для 0.5 можно создать константу. Или принимать это значение как аргумент в функции

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +        if (level - 2.0 * p * p - 2.0) > 0:
Ну раз у тебя выражение level - 2.0 * p * p - 2.0 используется дальше ещё где-то, стоит куда-нибудь записать его и обозвать понятно

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    for i in range(0, len(level_points_x)):
for p in level_points_x

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    for i in range(len(level_points_x) - 1, -1, -1):
Тут аналогично. В Python'e в таких случаях никогда не используют for i in ...

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    if (len(level_points_y) > 0):
А зачем ты лишние скобки везде пишешь в условиях?
В Python'e пишут if x:, а не if (x):

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +            pyplot.plot(level_points_x, level_points_y, "blue")
Вообще, кучу кода с попыткой нарисовать линии уровня можно заменить одной строчкой, если ты почитаешь про plot.contour

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +steps = 0
Ну вот тут опять же, нужно всё это в функцию закинуть

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +        learning_rate *= 1.1
Магические константы

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +print("Ответ:", x, y)
Всё это круто, конечно. Но ты взял тут конкретные x и y, а потом под них подгонял параметры. Скорее всего, если взять немного другие начальные x и y, так хорошо не получится

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    pyplot.plot(list_x, list_y, "blue")
Ну тут всё те же замечания, что и в предыдущем задании

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    new_Q = 0
Плохое название

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    for i in range(len(X)):
for x, y in zip(X, Y):

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +def calculate_RMSE_fixed(_lambda): #do not use it on your own
Что это за функция вообще? Стоит удалить видимо

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    global Y
global использовать нельзя

2016-11-20 18:59 UTC, PavelOstyakov commented on Lab1.py
> +    len = 0
len уже занято под стандартную функцию len(). Очень плохо переопределять

2016-11-20 20:04 UTC, aakogtenkov commented on Lab1.py
> +import random
а можно сделать, чтобы не писать в каждой ячейке импорты?

2016-11-20 20:05 UTC, aakogtenkov commented on Lab1.py
> +Q1_list = [max(0, 1 - M) for M in Mx_list]
list = список
Q = значение функции. Да, название не очень, я его как-нибудь поправлю. Но догадаться вполне возможно, я считаю.

2016-11-20 20:08 UTC, aakogtenkov commented on Lab1.py
> +print("Ответ:", x, y)
Неправда, я не подгонял параметры под конкретные x, y. Если посмотреть дальше, то параметры в других случаях очень похожи на параметры в этом случае. В любом случае, можно же просто самому подставить другие значения x, y и проверить.

2016-11-20 20:09 UTC, aakogtenkov commented on Lab1.py
> +def calculate_RMSE_fixed(_lambda): #do not use it on your own
ну, я ее использовал для minimize_scalar

2016-11-21 04:18 UTC, PavelOstyakov commented on Lab1.py
> +import random
Конечно. Ты можешь импортировать всё, что тебе нужно в самой первой ячейке, к примеру.

2016-11-21 04:18 UTC, PavelOstyakov commented on Lab1.py
> +def calculate_RMSE_fixed(_lambda): #do not use it on your own
Ну тогда нужно её полностью переписать или удалить

2016-11-21 04:27 UTC, PavelOstyakov requested changes

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +print("Right answer: ", w, ";  err: ", RMSE_loss)
Тут такой же код у тебя, стоит либо написать функцию, либо вообще не строить заново это решение

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +RMSE_loss = 0
Те же замечания про константы

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +RMSE_loss /= (len(X))
rmse_loss

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +RMSE_loss /= (len(X))
И зачем тут скобки?

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +steps1 = 0
Плохое название

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +    for i in range(len(new_w)):
numpy умеет работать так: new_w -= learning_rate * gradient. Тогда не придётся писать цикл

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +w = numpy.array([1.4532, -1.245, 0.1057])
А откуда эти числа?

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +print("Second algo's answer: ", w, ";  err: ", RMSE_loss)
Странно получается. Вот у тебя одинаковый код очень много где написан. Там меняются совсем незначительные участки. Перепиши всё на функции

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +                gradient[j] += (-Y[i] * X[i][j])
Странно очень. Там ведь другая производная, зачем это условие?

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +    for i in range(0, len(X)):
for x, y in zip(X, Y):

2016-11-21 04:27 UTC, PavelOstyakov commented on Lab1.py
> +    global X
Снова global

2016-11-21 09:07 UTC, aakogtenkov commented on Lab1.py
> +w = numpy.array([1.4532, -1.245, 0.1057])
Ну, какие-то рандомные начальные данные. Можно поменять

2016-11-21 09:10 UTC, aakogtenkov commented on Lab1.py
> +print("Second algo's answer: ", w, ";  err: ", RMSE_loss)
Окей, мне тут сказали, что в юпитере можно выполнять ячейки по очереди, и вызывать функции, которые есть в других ячейках. Где-то в среду тогда буду разносить все на функции по разным ячейкам

2016-11-21 09:14 UTC, aakogtenkov commented on Lab1.py
> +                gradient[j] += (-Y[i] * X[i][j])
Чтобы не вылетало, если аргумент экспоненты слишком большой. Конечно, там можно брать ограничение не 10, а 100, например, но это не сильно влияет

2016-11-21 14:48 UTC, PavelOstyakov requested changes
Давай так. У тебя дальше много похожих ошибок, поэтому я их комментить не буду, надеясь, что ты их исправишь. Когда выложишь готовую версию (т.е. с учетом всех предыдущих замечаний), я посмотрю ещё раз.

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +                gradient[j] += (-Y[i] * X[i][j])
Тогда следует написать комментарий в коде

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +    for i in range(0, len(gradient)):
Опять же, тут numpy позволяет сделать так: gradient / length

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +    for i in range(len(gradient)):
А тут можно просто перемножить вектор сам на себя

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +input = open('train.csv', 'r')
Не, так не делается.
import pandas
data = pandas.read_csv("train.csv")

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +input = open('train.csv', 'r')
И всё, что ниже, можно удалять

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +for BATCH_SIZE in list_batch_size:
Тут это не константа, поэтому batch_size

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +    FEATURES_NUMBER = len(first_group[0])
Аналогично

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +    DATA_FOR_LEARNING_SIZE = 2050 #2050 from 1st and 2050 from 2nd
Странно, что ты определяешь константы внутри цикла

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +    w = numpy.array([random.random() for i in range(FEATURES_NUMBER)])
np.random.rand

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +    general_logistic_loss = MIN_LOSS + 100;
А почему +100 тут? Следует написать об этом

2016-11-21 14:48 UTC, PavelOstyakov commented on Lab1.py
> +        if (len(X) != BATCH_SIZE):
А такое вообще может быть?

2016-11-24 07:53 UTC, PavelOstyakov requested changes

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +    MU_X_1 = -numpy.random.uniform(3, 10)
Это не константы, раз ты им присваиваешь результат какой-то функции

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +                           numpy.random.normal(MU_Y_1, SIGMA, POINTS_NUMBER),
Какое-то странное выравнивание тут

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +                            numpy.random.normal(MU_Y_2, SIGMA, POINTS_NUMBER),
Тут аналогично

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +    Point1 = [MIN_X, (-w[2] - w[0] * MIN_X) / w[1]]
Плохое название

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +def draw_line(w, MIN_X, MAX_X, color = "b"):
Ну не может константа в качестве аргумента тут быть

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +def draw_line(w, MIN_X, MAX_X, color = "b"):
color="b" без пробелов вокруг знака равно

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +    return w
А почему бы сразу не написать return numpy.dot

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +svm_list = [max(0, 1 - M) for M in arg_list]
Тут M не константа

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +svm_list = [max(0, 1 - M) for M in arg_list]
Вместо M можно сделать margin

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +trajectory, steps = gradient_descent_simple(3.3, 7.1, 0.3, 0.001, 1000) #x, y, learning_rate, eps, max_steps
Вот тут в скобках не просто числа нужно написать, а так:
gradient_descent_simple(x=3.3, y=7.1, ...

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +                     func, func_x_derivative, func_y_derivative,
Сдвиг странный

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +    rmse /= len(X)
А если len(X) = 0?

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +def calculate_RMSE(w, X, Y):
calculate_rmse

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +def get_optimal_learning_rate_RMSE(w, X, Y, gradient): #just calculate derivative and compare it with 0 to find best LR
Не пишем мы большие буквы в названии функции

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +    for i in range(0, len(X)):
for x, y in zip(X, Y):

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +def gradient_descent(w, X, Y, learning_rate, EPS, MAX_NUMBER_STEPS,
eps, max_iter

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +        if (numpy.dot(gradient, gradient) < EPS):
Не if(x):, а if x:

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +pyplot.plot([i for i in range(len(loss_list1))], loss_list1, "blue")
А почему не list(range(len))

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +        elif (elem[0] == 0):
Без скобок

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +def load_data():
Воспользуйся возможностями numpy сразу найти все нужные индексы. Тогда не нужно будет писать цикл

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +                gradient[j] += math.exp(-Y[i] * numpy.dot(w, X[i])) / (1 + math.exp(-Y[i] * numpy.dot(w, X[i]))) * (-Y[i]) * X[i][j]
Очень длинная строка, а самое главное - непонятная. Нужно разбить

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +            ans += (-Y[i] * numpy.dot(w, x))
А что такое i?

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +    logistic_loss = 1000000000000
А зачем вообще эта переменная?

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +for i in range(len(list_results)):
Это нужно переделать

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +    return (0, 0)
return 0, 0

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +        return (x / len, y / len)
return x / len, y / len

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +        return (x / len, y / len)
А если len = 0?

2016-11-24 07:53 UTC, PavelOstyakov commented on Lab1.py
> +_GAMMA = 0.85
Весь дальнейший код переписываем на функции

2016-11-24 17:14 UTC, aakogtenkov commented on Lab1.py
> +    Point1 = [MIN_X, (-w[2] - w[0] * MIN_X) / w[1]]
Да что не так с названием? Отрезок состоит из 2 точек. Любому человеку очевидно, что если в функции из 3 строк, которая рисует отрезочек, есть 2 переменные с названиями "точка 1" и "точка 2", то наверное эти точки образуют отрезок

2016-11-24 17:14 UTC, aakogtenkov commented on Lab1.py
> +    return w
Чтобы было понятнее, что возвращается.

2016-11-24 17:15 UTC, aakogtenkov commented on Lab1.py
> +        if (numpy.dot(gradient, gradient) < EPS):
да хватит уже

2016-11-24 17:17 UTC, aakogtenkov commented on Lab1.py
> +                gradient[j] += math.exp(-Y[i] * numpy.dot(w, X[i])) / (1 + math.exp(-Y[i] * numpy.dot(w, X[i]))) * (-Y[i]) * X[i][j]
если я ее разобью, она не станет понятнее. Это просто производная сложной функции. Она не должна быть понятной. Наоборот, я считаю, разбиения таких вещей дают человеку ложное впечатление, что куски этой штуки имеют какой-то смысл.

2016-11-24 18:34 UTC, aakogtenkov commented on Lab1.py
> +for i in range(len(list_results)):
а что конкретно в этой строке надо переделать?

2016-11-27 16:43 UTC, PavelOstyakov requested changes

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +def create_clouds(POINTS_NUMBER):
В данном случае POINTS_NUMBER -- это не константа

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +def gradient_descent_simple(x, y, learning_rate, EPS, MAX_NUMBER_STEPS, deceleration = 0.5):
Тут EPS и MAX_NUMBER_STEPS не являются константами

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +def gradient_descent_simple(x, y, learning_rate, EPS, MAX_NUMBER_STEPS, deceleration = 0.5):
deceleration=0.5 (без пробелов вокруг знака равно в аргументе функции)

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +        new_RMSE = func(w, X, Y)
new_rmse

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +            print("CRITICAL ERROR: THE PROGRAM CANNOT READ THIS FILE")
Тогда стоит писать это в stderr, а не в stdout

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +def create_batch(first_group, second_group, batch_size, features_number, data_for_learning_size, step_num):
Функция с очень странным поведением. Сделай лучше генератор, который будет отдавать данные необходимого размера.

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +def get_number_errors(w, X, Y):
Тогда лучше сделать accuracy_score

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +    while steps < max_number_steps and general_error > min_error: #means that there are used (BATCH_SIZE * MAX_NUMBER_OF_STEPS) % DATA_FOR_LEARNING_SIZE elems from data
Смести комментарий, раз он не помещается на данной строке

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +list_batch_size = [30, 70, 100, 150, 200, 300]
Это как раз константа, ниже тоже

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +for i in range(len(list_results)):
Тут используем zip

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +    pyplot.plot([list_batch_size[i] * j for j in range(0, len(list_results[i]))], list_results[i], list_colors[i])
В range можно не писать 0, просто range(len)

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +pyplot.plot(range(5, len(list_error)), list_error[5:], "blue")
А почему тут от 5?

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +        for i in range(0, len(w)):
Опять же, давай с помощью numpy.array просто напишем new_w = w - learning_rate * gradient

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +        if (calculate_logistic_func(new_w, X, Y) >= logistic_loss):
Скобки убери лишние, выше тоже много мест таких

2016-11-27 16:43 UTC, PavelOstyakov commented on Lab1.py
> +MATRIX_FEATURES = numpy.vstack((numpy.array(first_group), numpy.array(second_group)))
Это не константа. Ниже то же самое

2016-11-27 18:06 UTC, aakogtenkov commented on Lab1.py
> +def create_batch(first_group, second_group, batch_size, features_number, data_for_learning_size, step_num):
а что подразумевается под странным поведением?
Я не очень понял по поводу генератора. Вот эта функция берет считанные данные и выдает step_num-ый блок размера batch_size.

2016-11-27 18:07 UTC, aakogtenkov commented on Lab1.py
> +pyplot.plot(range(5, len(list_error)), list_error[5:], "blue")
просто чтобы графики были красивыми, а иначе они очень прижаты к осям

2016-11-27 20:10 UTC, PavelOstyakov commented on Lab1.py
> +pyplot.plot(range(5, len(list_error)), list_error[5:], "blue")
Тут по идее можно использовать pyplot.ylim

2016-11-27 20:13 UTC, PavelOstyakov commented on Lab1.py
> +def create_batch(first_group, second_group, batch_size, features_number, data_for_learning_size, step_num):
Ну смотри, было бы круто сделать всё так:

```
w = initial weights
for X, Y in batch_generator(data, batch_size):
    gradient_descent(w, X, Y) # update weights

```

Тогда и кода станет меньше, и всё будет понятнее написано для внешнего читателя.

2016-11-28 07:31 UTC, aakogtenkov commented on Lab1.py
> +def create_batch(first_group, second_group, batch_size, features_number, data_for_learning_size, step_num):
Ну тут проблема в том, что структура может очень много весить, если мы много блоков берем, по идее

2016-11-28 17:41 UTC, aakogtenkov commented on Lab1.py
> +def get_number_errors(w, X, Y):
честно говоря, accuracy_score мне не очень нравится, поскольку название "оценка точности" слишком мало говорит. Мне хотелось бы сделать упор на то, что здесь именно количество ошибок возвращается, а не значение какой-нибудь странно вычисляемой сложной формулы оценки.

2016-12-01 08:37 UTC, PavelOstyakov requested changes

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +                             deceleration = 0.5, acceleration = 1.1):
deceleration=0.5, acceleration=1.1

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +trajectory, steps = updated_gradient_descent(x=-3.05, y=2.05, learning_rate=1, EPS=0.000005, MAX_NUMBER_STEPS=100000,
eps, max_number_steps

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +pyplot.contour(grid_x, grid_y, grid_z, levels, colors = "b")
colors="b"

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +levels = [1, 5, 10]
LEVELS

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +        if (new_rmse >= rmse):
if a:, а не if(a):

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +def create_batch(first_group, second_group, batch_size, features_number, data_for_learning_size, step_num):
Какая структура? И почему она должна много весить?

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +def create_batch(first_group, second_group, batch_size, features_number, data_for_learning_size, step_num):
Ты в любом случае тут ровно столько же памяти используешь, но код будет в 1000 раз красивее и понятнее

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +def get_number_errors(w, X, Y):
Я имел в виду не просто переименовать функцию. Дело в том, что если у тебя меняется количество элементов в выборке, то хотелось бы уметь оценивать твой алгоритм всё равно. Если ты будешь считать количество ошибок, то это будет плохая оценка. Пример: ты удвоишь количество объектов в выборке, у тебя примерно удвоится количество ошибок. А если ты это количество каждый раз будешь делить на число объектов в выборке, то у тебя примерно константная ошибка будет получаться.

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +MATRIX_FEATURES = numpy.vstack((numpy.array(first_group), numpy.array(second_group)))
Это не константы

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +def momentum_method(x, y, learning_rate, eps, max_number_iters, func, func_derivative, GAMMA=0.85):
gamma

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +def nesterov_accelerated_gradient(x, y, learning_rate, eps, max_number_iters,
Лучше сделать более общую штуку, когда у тебя не две переменные, а много.

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +def nesterov_accelerated_gradient(x, y, learning_rate, eps, max_number_iters,
И желательно во всех градиентных методах, которые ты тут писал. Тогда будет потом удобно любые данные загонять в них

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +def stohastic_gradient_descent_simple(first_group, second_group, batch_size, max_number_steps,
Как-то тут много очень аргументов у функции. Посмотри внимательно, может что-то избыточное.

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +            new_w[i] -= learning_rate * bias_corrected_first[i] / (eps + math.sqrt(second_momentum[i][i] / (1 - second_coeff_powered)))
Строка не помещается, стоит её разбить

2016-12-01 08:37 UTC, PavelOstyakov commented on Lab1.py
> +            new_w[i] -= learning_rate * bias_corrected_first[i] / (eps + math.sqrt(second_momentum[i][i] / (1 - second_coeff_powered)))
И остальные длинные строчки тоже

2016-12-01 15:23 UTC, aakogtenkov commented on Lab1.py
> +def nesterov_accelerated_gradient(x, y, learning_rate, eps, max_number_iters,
У нас задание - покопаться в том, как работает. Поэтому я везде, где можно, сделал переменные x, y.

2016-12-01 15:25 UTC, aakogtenkov commented on Lab1.py
> +def stohastic_gradient_descent_simple(first_group, second_group, batch_size, max_number_steps,
да нет, вроде все используется.

2016-12-01 15:34 UTC, aakogtenkov commented on Lab1.py
> +MATRIX_FEATURES = numpy.vstack((numpy.array(first_group), numpy.array(second_group)))
Насчет create_batch. Я считаю, что способ, которым я создаю батч, является самым прозрачным. Если мы создаем батчи отдельно друг от друга, то да, приходится передавать туда много аргументов. Это на самом деле позволяет нам как-то контролировать процесс. Если мы сразу создаем набор батчей, то это занимает сильно больше памяти.

2016-12-01 17:00 UTC, aakogtenkov commented on Lab1.py
> +MATRIX_FEATURES = numpy.vstack((numpy.array(first_group), numpy.array(second_group)))
Насчет get_number_errors. Несложно заметить, что программы выводят строку вида "Ошибок: n / N". То есть показывается то, что нужно.
Просто так у нас есть чуть больше гибкости: можно в случае чего просто вывести именно количество ошибок, а не соотношение.

2016-12-02 09:41 UTC, PavelOstyakov commented on Lab1.py
> +MATRIX_FEATURES = numpy.vstack((numpy.array(first_group), numpy.array(second_group)))
Зачем создавать сразу много батчей? Я же написал, что нужно сделать генератор. Почитай, как они работают тут: https://wiki.python.org/moin/Generators
У Питона идеалогия такая, что используются всегда высокоуровневые конструкции.

2016-12-02 09:44 UTC, PavelOstyakov commented on Lab1.py
> +MATRIX_FEATURES = numpy.vstack((numpy.array(first_group), numpy.array(second_group)))
Про get_number_errors: ок, но так никто не делает никогда. Вообще, тебе будет полезно почитать про метрики качества классификации: http://machinelearningmastery.com/classification-accuracy-is-not-enough-more-performance-measures-you-can-use/

2016-12-02 09:47 UTC, PavelOstyakov requested changes

2016-12-02 09:47 UTC, PavelOstyakov commented on Lab1.py
>  print("Used elements: ", len(list_errors) * BATCH_SIZE)
Странно получается. То есть могло получиться так, что ты не все объекты используешь?

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    MU_X_1 = -5
Лучше группировать по точкам, а не осям, так будет понятнее.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    first_cloud = numpy.array([numpy.random.normal(MU_X_1, SIGMA, points_number),
В numpy есть сразу многомерное распределение. А тут ты как бы себя сам ограничиваешь, твои облачка могли бы быть вытянуты по диагонали, к примеру :)

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +                                [1] * points_number])
Избегай операции умножения списка, когда будешь работать с большими объемами данных. Лучше сразу создать массив **np.ones**.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    left_point = [min_x, (-w[2] - w[0] * min_x) / w[1]]
А вот тут проще и понятнее **X** и **Y** хранить в разных списках, все равно же их придется формировать, чтобы отдать на отрисовку. Да и код вычисления **Y** не пришлось бы тогда дублировать.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +def draw_line(w, min_x, max_x, color="b"):
Эта функция не умеет рисовать вертикальные линии ;)

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    tmp = numpy.linalg.inv(numpy.dot(X.T, X)) #(X^T * X)^(-1)
Кстати, у этой штуки, если я правильно помню, если свое имя _"псевдообратная матрица"_, можно было использовать.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    return w
Паша прав, лучше назови хорошо функцию, тогда будет понятно, что там возвращается ;)

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +POINTS_NUMBER = 100
Со временем я пришел к выводу, что тут лучше писать нормальную форму существительного, от этого _S_ все равно смысла не прибавляется, а вот если бы это был массив точек, то лучше написать _points_.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +Y = (numpy.hstack(([-1] * POINTS_NUMBER, [1] * POINTS_NUMBER))).transpose()
тут тоже можно было использовать **np.ones(POINTS_NUMBER)** и  **- np.ones(POINTS_NUMBER)**.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +# Несложно видеть, что если всего точек было $n$, то сложность обучения составляет $O(n)$. Действительно, мы проделываем константное количество операций с матрицами, при этом все матрицы (в том числе
Так-то оно так, но иногда размерность вектора бывает велика, поэтому это значительно влияет на итоговое время работы алгоритма. Стоило все же ее учитывать, константа там не шуточная может быть.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +def gradient_descent_simple(x, y, learning_rate, eps, max_number_iters, deceleration=0.5):
хммм.. какой-то накрученный у тебя спуск, ну да ладно.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +def rosen_x_derivative(x, y):
Можно было вектор numpy возвращать, тогда не пришлось бы дублировать код везде.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +print("Ответ:", x, y)
Вот здесь вот не хватате **x-а**, поэтому ячейка не исполняется.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +# На графике выше синим цветом обозначены 3 линии уровня (для $f=1,5,10$); красной линией обозначено, как в процессе работы изменяются значения текущих координат. Видно, что после довольно короткого
Круто, что функцию ты поборол, но слишком ручная получилась функция оптимизации ) много параметров, которые надо настраивать.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +trajectory, steps = updated_gradient_descent(x=-3.05, y=2.05, learning_rate=1, eps=0.000005, max_number_iters=100000,
Вот общее замечание, хотелось бы в качестве критерия остановки все же иметь сходимость именно  к локальному минимуму, а не количество итераций. Хотя "отстреливать" работу алгоритма, если слишком долго ищем, тоже не такая плохая идея, но там в качестве границы надо ставить экстремальные значения.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        print("oO")
Лучше бросать exception c сообщением "WTF, man? Length of X is zero o0"

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    for point in X:
Да можно прям в одном цикле, тогда *numpy.dot(gradient, x)* не нужно будет дважды считать,

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        for j in range(0, len(gradient)):
Он прекрасно записывается в виде векторных произведений.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        if (numpy.dot(gradient, gradient) < eps):
Здесь и ниже дважды считаешь норму.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        if numpy.dot(gradient, gradient) < eps:
и здесь дважды считаешь норму.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +pyplot.show()
График сложный, уже не хватает легенды.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +            print("CRITICAL ERROR: THE PROGRAM CANNOT READ THIS FILE")
Странная штука, лучше выкинуть ее :)

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +            tmp = list(elem[1:])
Зачем срез еще раз в list  оборачивать?

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +            tmp = list(elem[1:])
Первые два шага повторяются, их стоит вынести наверх вне условия.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +                gradient[j] += math.exp(-Y[i] * numpy.dot(w, X[i])) / (1 + math.exp(-Y[i] * numpy.dot(w, X[i]))) * (-Y[i]) * X[i][j]
Это не правда, просто ты не читаешь чужой код :)

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +def create_batch(first_group, second_group, batch_size, features_number, data_for_learning_size, step_num):
Полностью поддерживаю Пашу.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    for i in range(0, batch_size // 2):
Функция предполагает, что batch_size всегда четный.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    for i in range(0, len(X)):
Расписывается  через векторные произведения.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        if (-y * numpy.dot(w, x) > 10): #anti overflow
С этим борются по до другому обычно, я тогда присылал gist.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +def get_number_errors(w, X, Y):
В точку.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        if (-y * numpy.dot(numpy.array(w) - learning_rate * numpy.array(gradient), x) > 10): #anti-overflow
Часто одну и ту же математику считаешь по несколько раз, это неэффективно.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    general_error = min_error + 1 #this value allows use do execute 'while' below at least 1 time
Не-не, такой код не нужен, нужно относительно количество ошибок указывать. Да даже если так, то зачем единицы то добавлять? у нас есть нестрогое сравнение.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    first_group = [] #0
Вместо давать комментарии, надо нормально называть переменные.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +def stohastic_gradient_descent(first_group, second_group, batch_size, max_number_steps,
Очень странный интерфейс, обычно классы идут вперемешку в одно матрице и есть отдельно вектор с ответами.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        general_error = get_number_errors(w, matrix_features, matrix_answers)
Как обычно делают. Считают ошибку на текущем батче, а только потом на нем обучаются. Это вам и предлагалось сделать.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +MATRIX_FEATURES = numpy.vstack((numpy.array(first_group), numpy.array(second_group)))
Почему нет реакции на слова ревьюера? Не константы мы не пишем большими буквами.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    w, list_errors = stohastic_gradient_descent(first_group=first_group,
уже плохо читается, я предлагаю писать такие вещи так

```
result = some_function(
   arg1 = value1,
   arg2 = value2,
   ...
)
```

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +for result, batch_size, color in zip(list_results, LIST_BATCH_SIZE, LIST_COLORS):
Подписи осей, легенда.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +pyplot.plot(range(5, len(list_error)), list_error[5:], "blue")
В точку.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +    learning_rate = eps + 1
Я понял для чего, но лучше избегать таких трюков.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +x, y, list_error = steepest_gradient_simple(x=2, y=-33, eps=0.00005, max_number_iters=1000,
Пиши в колонку аргументы.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        w = copy.copy(new_w)
А зачем именно копировать? кажется все можно было сделать inplace.

2017-02-13 17:12 UTC, dasimagin commented on Lab1.py
> +        G_matrix += gradient.transpose() * gradient
Кажется, там не обязательно было всю матрицу вычислять :)

2017-03-19 19:13 UTC, merged